### PR TITLE
Enforce `.editorconfig` line-ending settings

### PR DESCRIPTION
**Pull request by Repiteo**
Swept through the repo and enforced the basic `.editorconfig` settings. Additionally, sets appropriate settings in `.gitattributes` to mirror the config & ignores the conversion commit via `.git-blame-ignore-revs`. No functional changes were made, so the contributor checklist isn't applicable.

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
You will need to add a blurb to RELEASE.txt and CHANGE.txt
This massive formatting change may cause conflicts with outstanding PRS and/or other's checked out trees..

**Comment by mwichmann** [comment]
We *do* want to do a reformat - if we're going to do it, we've talked about running black on everything, which may or may not do more than what the summary of this PR implies.  Inlcuding the git ignore-revs thing as you've done. So this is Good - but what @bdbaddog was getting at was it's a timing question. We've delayed it many times because even though you can fix "git blame", it's still quite disruptive.

Also one specific note: the docbook-xsl tree is an imported repo, not our code (if being setup today it would either be a separate (fork) tree of the upstream and probably built with our glue file together as an addon package to SCons; or setup as a submodule (or subtree).  It's going to need rebasing someday, so we try to not touch it at all except for outright breakage.  

We haven't really talked about the same kind of reformatting to other files than Python... the .xml doc files, for example, are kind of all over the place.  Since I took the initial shot at an editorconfig new content is consistent in *my* editor, which listens to it. But there seem to have been a lot of styles in use throughout the doc sources.

**Comment by Repiteo** [comment]
I could walk the scope back to specifically line-endings. That'd be far less disruptive, and changing the `.gitattributes` will mean any rebases get automatically resolved

**Comment by Repiteo** [comment]
There we go! Now the *only* file changes are ensuring the correct line-endings. This cuts down **significantly** on the amount of disruption, affecting less than a tenth of the files as last time.

**Comment by Repiteo** [comment]
Actually, it seems that the bulk of files that needed to be converted were only very recently affected: #4544 seems to be what initially caused most of the files to have `\r\n` eol.

**Comment by bdbaddog** [comment]
That looks good.
You still need a CHANGES.txt/RELEASE.txt blurb.
Then I'll be able to merge.

**Pull request merged**
