### PR TITLE
Use f-strings in framework and framework tests

### PR DESCRIPTION
**Pull request by mwichmann**
This is a mostly tool-based conversion (a couple added by hand), and other changes were not made, to try to keep the diff manageable.

Adds a GitHub Action to run framework tests if framework changes. Because of this, the existing fails in the framework tests need to be fixed before we can get to a "pass" status.  

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Thanks to @bdbaddog the exception-raising test in `TestCommonTests` now passes on 3.11 as well - the version the GitHub action was set up with. It was previously passing on older Pythons, but the "friendlier error messages" stuff in 3.11 adds more output to (some) exceptions and so was still failing.

There are two fails left in `TestCmdTests`, as follows:

* `test_finish`: 
  ```
    File "/home/mats/github/scons/testing/framework/TestCmdTests.py", line 2510, in test_finish
      assert stdout == expect_stdout, stdout
  AssertionError: script_recv:  STDOUT
  ```
* `test_send()`: 
  ```
    File "/home/mats/github/scons/testing/framework/TestCmdTests.py", line 2608, in test_send
      assert result == expect, f"Result:[{result}] should match\nExpected:[{expect}]"
  AssertionError: Result:[] should match
  Expected:[script_recv:  stdin.write() input to the receive script
  ```

There are two of the only three tests that use the `send` functionality; the third one is marked flaky: 
```py
    # TODO(sgk):  figure out how to eliminate the race conditions here.
    def __FLAKY__test_send_recv(self):
```

**Comment by mwichmann** [comment]
Probably should use the unit test skip decorator rather than inline os check

**Comment by bdbaddog** [comment]
> Probably should use the unit test skip decorator rather than inline os check

Agree. Couldn't remember/find the syntax and since I had to throw away my previous fix with the git madness... ;)
What's the right syntax?

**Comment by mwichmann** [comment]
> > Probably should use the unit test skip decorator rather than inline os check
> 
> Agree. Couldn't remember/find the syntax and since I had to throw away my previous fix with the git madness... ;) What's the right syntax?

`@unittest.SkipIF`

I'm looking at these now, looks like a couple shouldn't necessarily skip the whole test, but the existing test was insufficient: looks for `os.symlink` in a try block, but windows *has* it now, it just isn't useful unless you have special conditions set up.

**Comment by bdbaddog** [comment]
> > > Probably should use the unit test skip decorator rather than inline os check
> > 
> > 
> > Agree. Couldn't remember/find the syntax and since I had to throw away my previous fix with the git madness... ;) What's the right syntax?
> 
> `@unittest.SkipIF`
> 
> I'm looking at these now, looks like a couple shouldn't necessarily skip the whole test, but the existing test was insufficient: looks for `os.symlink` in a try block, but windows _has_ it now, it just isn't useful unless you have special conditions set up.

RIght, but simpler to just skip the test or part of the test which required symlink.
We're testing it on linux and we don't natively use symlinks on windows, so I'm fine with not spending tons of time figuring out how to check if the current user has permissions to symlink and to symlink the current dir/etc.. it seems like a rathole not worth resolving.

**Pull request merged**
