### PR TITLE
Windows clang tests

### PR DESCRIPTION
**Pull request by dmoody256**
On windows, a SCons environment will only include the system32 path, unless default windows environment is used in which case the path is setup from the vcvars batch script.

The clang test do not use the msvs environment and therefore do not have the clang or other necessary cygwin binaries in the path when scons goes to build.

This pull request updates the test to add the correct binaries to the path, and skips tests that are meant to use the default environment.

## Contributor Checklist:

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Would we better off with more reasonable default installation directories for clang on windows? (which would resolve this without the need for changing the tests?)

**Comment by dmoody256** [comment]
That would probably be the better solution. I wasn't sure the scons way to implement this though.

Would I add some common default paths for clang and cygwin (checking for existence?) or would I look at the current os.environ PATH to find the location of the binaries if they exist, or a combination of both?

**Comment by bdbaddog** [comment]
Changing the logic to have some reasonable default locations would be o.k but importing os.environ's PATH by default is generally not SCons'ian

**Comment by dmoody256** [comment]
Closing this pull request to reopen with the changes in clang tool to use some default paths for clang and cygwin on windows.

**Comment by bdbaddog** [comment]
This is my work in progress for this issue: 
https://github.com/SCons/scons/pull/3052

**Pull request closed without merging**
