### PR TITLE
Change appendenvpath default

### PR DESCRIPTION
**Pull request by dmoody256**
Potential solution for https://github.com/SCons/scons/issues/3276

Change the default to not touch the path.

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Looks like there's a test that depends on the old default behavior.

**Comment by dmoody256** [comment]
I checked the related documentation in the man page, and it looks like its correct already, so that means the code before this PR was not in line with the documentation.

**Comment by bdbaddog** [comment]
I thought the docs didn't specify the default for delete_.. parameter?

**Comment by dmoody256** [comment]
> I thought the docs didn't specify the default for delete_.. parameter?

They don't say an explicit default value, but they do describe the default behavior as:
> _This will only add any particular path once (leaving the last one it encounters and ignoring the rest, to preserve path order)_

**Comment by bdbaddog** [comment]
So this is ready to merge right?
mingw failure expected at this point?

**Comment by dmoody256** [comment]
Yeah, this ones good to go

**Pull request merged**
