### PR TITLE
Initial logic for Sphinx build of API docs  - replacing epydoc 

### LINKED ISSUE #3604: Switch SCons APIDOCS from epydoc to Sphinx
See Issue #3121 for history

epydoc is no longer maintained.
Switch to sphinx

### PR DESCRIPTION
**Pull request by mwichmann**
General setup for Sphinx build - config, style, etc.

A few regular scons files are updated to address build errors/warnings.

TODO: 
* [ ] integrate the Makefile steps into scons' own scripts - Can punt on this for the initial checkin.  Just update the https://github.com/SCons/scons/wiki/SimplifiedReleaseProcedure and file an enhancement so we don't lose this.
* [x] epydoc did not present Tool modules, should we? - No. we didn't previously.
* [x] decide whether to document private and/or special methods - No.
* [x ] decide path where built docs should end up - `build/doc/API`
* [ ] document doc building - Add to : https://github.com/SCons/scons/wiki/SimplifiedReleaseProcedure
* [ ] pick/document docstring conventions 

Specific errors:
* [ ] modules containing ++ in filename cause errors (and, indeed, syntactically this is not legal in Python). SCons has a remapping mechanism, but it's not quite that simple. `aixc++, c++, g++, hpc++, sgic++, sunc++`
* [x] `index.rst:9: WARNING: toctree contains reference to nonexisting document 'SCons.Tool.packaging.'`
* [ ] `WARNING: autodoc: failed to determine Null(0x7F706BF19210) to be documented.the following exception was raised: cannot unpack non-iterable Null object` (SCons' Null is a hack - no checkers like it either)

Fixes #3604 #3121 

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `src/CHANGES.txt` (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Re: docstring style. Didn't we discuss using Googles style?

**Comment by bdbaddog** [comment]
RE: "++" modules, can we get Sphinx to ignore them?

**Comment by mwichmann** [comment]
> RE: "++" modules, can we get Sphinx to ignore them?

in a way... by not looking deeper in Tools, they do get ignored, but I can't call them out by name to be ignored for the same reason they cause trouble if processed.

**Comment by mwichmann** [comment]
> Re: docstring style. Didn't we discuss using Googles style?

Yes, and that's what I've been using recently.

**Comment by bdbaddog** [comment]
I think if you add a blurb to the wiki page and assuming I can just do ```make somearg``` I'd be ready to merge this one.

**Pull request merged**
