### PR TITLE
Do not overwrite LINKFLAGS if user set it

### PR DESCRIPTION
**Pull request by mwichmann**
The `link.py` tool unconditionally set `LINKFLAGS` (and `LINK`), keep existing values if user tried to set them.

Fixes issue #2357

No attempt to fix this generally - there are lots of tools which set something without checking, and the referenced issue has some discussion of making a special type that does a bit better. Leave that topic for another time.

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Okay, doing that to `LINK` was apparently a step too far for unittests.  Should I roll that back out? It's the test for the `Tool` method, and seems quite determined that `LINK` will be forced to `$SMARTLINK` - I would have thought if someone went to explicitly set `LINK`, it should stick... Here's the relevant part of the unit test:
```python
    def test_Tool(self):
        """Test the Tool() method"""
        env = self.TestEnvironment(LINK='link', NONE='no-such-tool')
...    
        env.Tool('$LINK')
        assert env['LINK'] == '$SMARTLINK', env['LINK']
```

**Comment by bdbaddog** [comment]
> Okay, doing that to `LINK` was apparently a step too far for unittests. Should I roll that back out? It's the test for the `Tool` method, and seems quite determined that `LINK` will be forced to `$SMARTLINK` - I would have thought if someone went to explicitly set `LINK`, it should stick... Here's the relevant part of the unit test:
> 
> ```
>     def test_Tool(self):
>         """Test the Tool() method"""
>         env = self.TestEnvironment(LINK='link', NONE='no-such-tool')
> ...    
>         env.Tool('$LINK')
>         assert env['LINK'] == '$SMARTLINK', env['LINK']
> ```

Which test file is that?

**Comment by mwichmann** [comment]
`SCons/EnvironmentTests.py`

**Comment by mwichmann** [comment]
Any thoughts?  After a recent change, the docs now suggest you probably don't want to change `LINK`, but I'd expected it to honor what it was set to, no?

**Comment by bdbaddog** [comment]
I guess one of two things should happen.
1. It should respect the users settings
2. If not, it should alert the user that it's being discarded..

I'd vote for #1.
but maybe put a big notice in CHANGES.txt and RELEASE.txt what the impact may be? 
If there are builds in the wild setting LINK, but having it ignored, it may be that they break when this change rolls out.
So something to help fix such. Maybe a note like "if your build's link steps stop working, please check your LINK, as this release stopped ignoring those settings during tool initialization" ?

**Comment by mwichmann** [comment]
Every time I glance at this, it's fascinating how many of the tools just set key variables unconditionally, so there's always this itch to go change more. Must resist...

I think the answer here is to abandon the attempt to preserve an existing setting of `LINK`.  I had not looked at the Windows CI run once I saw the basic error on the Linux side in `EnvironmentTests`.  Two mingw (e2e) tests fail, and it appears that mingw working depends on the value of `LINK` evaluating to `smart_link`, even if it might have been set by something else earlier in initialization?

These two errors:

```
gcc -o foo.o -c foo.c
link -o foo.exe /nologo foo.o
Microsoft (R) Incremental Linker Version 14.00.24241.7
Copyright (C) Microsoft Corporation.  All rights reserved.
LINK : warning LNK4044: unrecognized option '/o'; ignored
LINK : fatal error LNK1181: cannot open input file 'foo.exe'
scons: building terminated because of errors.
```
and

```
link /nologo -shared -o shared.dll shared.o $(  $)  -Wl,--out-implib,libshared.a
LINK : warning LNK4044: unrecognized option '/shared'; ignored
LINK : warning LNK4044: unrecognized option '/o'; ignored
LINK : warning LNK4044: unrecognized option '/Wl,--out-implib,libshared.a'; ignored
LINK : fatal error LNK1181: cannot open input file 'shared.dll'
scons: building terminated because of errors.
```

Both indicate the Microsoft linker has been called instead of `gcc`, as would have been the case if the `smart_link` semantics remained in place.  So if mingw matters (I assume it does), this will require more tracing and rework to fix. Roll out and leave for some other time, possibly never?

**Comment by mwichmann** [comment]
I think it's time to give up on this.  I'm chasing my tail on part of it - the changes to the three tests in `test/sconsign/script` to insert Python as the program runner, rather than expecting `fake_link.py` and `fake_cc.py` completely throws off the emitted `sconsign` information, which expects to have the mock compiler and linker in the dependencies, not a path-to-Python.

Meanwhile, preserving `LINKFLAGS`, the original complaint this is responding to, doesn't work in the Windows CI setup, which finds the MSVC tools, and thus initializes with `mslink` tool, which runs this line:
```python
env['LINKFLAGS'] = SCons.Util.CLVar('/nologo')
```
Thus when we initialize the `link` tool for mingw, as is done in, for example, `test/LEX/live_mingw.py` like this:
```python
foo = Environment(tools=['default', 'mingw', 'lex'], LEXUNISTD="")
```
we come in with `LINKFLAGS` set, and it keeps it, and the test fails with:
```
lex -t foo.l > foo.c
gcc -o foo.o -c foo.c
gcc -o foo.exe /nologo foo.o
scons: building terminated because of errors.
STDERR =========================================================================
gcc: error: /nologo: No such file or directory
scons: *** [foo.exe] Error 1
```
So while this test passes fine on a mingw-only system, it doesn't work on a system were both msvc and mingw are provisioned.

I'm not sure it's worth the time to unravel this chain of interactions at present (there are a ton of issues tagged mingw, maybe at some point if those are addressed en masse....)

**Comment by mwichmann** [comment]
Going to file a few of the needed test changes separately, and give up on this one for now - withdrawing.

**Pull request closed without merging**
