### PR TITLE
Reduce travis texlive install footprint

### PR DESCRIPTION
**Pull request by dmoody256**
The travis install script install all the langs and docs for latex tools. not installing this saves hundreds of MB of download and installing, and is not used any tests anyways.

## Contributor Checklist:

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
So it's now only installing the bits used by the tests?

**Comment by dmoody256** [comment]
yeah, should save off like a minute or two from install time during the test

**Comment by bdbaddog** [comment]
O.k Thanks! I was wondering about that. Did that package get a lot bigger lately, because it didn't used to take so long..

Merging.

**Comment by dmoody256** [comment]
Idk but looking back at the older builds, it may have taken off closer to 5 mins of dependency install time, with total dependency install time taking usually around 10 mins

**Pull request merged**
