### PR TITLE
typo in customized decider example in user guide.

### PR DESCRIPTION
**Pull request by swuecho**
credit: https://stackoverflow.com/questions/39856184/does-scons-customized-decider-function-require-to-be-class-member

### CODE REVIEW

**Comment by swuecho** [comment]
@bdbaddog  If it is not a strict policy, probably too small change to worth another commit.

**Comment by bdbaddog** [comment]
I like to call attention all committers and also to changes in documentation. Please make the addition to the src/CHANGES.txt. Thanks!

**Comment by swuecho** [comment]
@bdbaddog  thanks. updated.

**Comment by bdbaddog** [comment]
thanks!

**Pull request merged**
