### PR TITLE
WIP: Fix ninja warnings/exceptions

### LINKED ISSUE #4036: ninja tool: using SCons warnings framework incorrectly
(Edited to update) When I revisited a long pending set of checker gripes about the use of warnings, saw there are two instances in the ninja tool where a warning class is instantiated, but then nothing is done with it - it's not assigned to anything, it's not directly raised. Two other instances directly raise it, meaning it's not really a "warning" - it's actually an exception, it just happens to be the `SConsWarning` exception, which doesn't really make a lot of sense.

Instantiated, unused:
https://github.com/SCons/scons/blob/120b2cd0b71363f63e8eb4898a44f1ba8a48af64/SCons/Tool/ninja/NinjaState.py#L810C1-L816C10
https://github.com/SCons/scons/blob/120b2cd0b71363f63e8eb4898a44f1ba8a48af64/SCons/Tool/ninja/__init__.py#L235

The first of those does intend a warning, it executes code after the call to the class constructor. The second looks like it actually wanted to raise an exception.

Directly `raise`:
https://github.com/SCons/scons/blob/120b2cd0b71363f63e8eb4898a44f1ba8a48af64/SCons/Tool/ninja/__init__.py#L164
https://github.com/SCons/scons/blob/120b2cd0b71363f63e8eb4898a44f1ba8a48af64/SCons/Tool/ninja/__init__.py#L201

These two clearly intend execution to stop.

To fully use the scons framework you define a warning class and assign it to one of the categories (by inheriting from either `SConsWarning` or `WarningOnByDefault`) and then invoke it in the desired way by calling `SCons.Warnings.warn()` (though that's not absolutely necessary). Ninja *does* define its own warning:

```py
class NinjaExperimentalWarning(SCons.Warnings.WarningOnByDefault)
```
but it is never used.

### PR DESCRIPTION
**Pull request by mwichmann**
Try to normalize errors/warnings.  One warning which was just a bare class instantition (thus, a no-op) now warns; two failures which used to raise `SConsWarning` now raise `ImportError` since that's what they are (has no visible effect to the user); another now raises `UserError`, as it is raised for an error in SConscripts.

There are no API or documentation impacts of this change, just consistency.

Fixes #4036

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Ah.  This fails tests, because there are places where the warning (that wasn't previously raised) is triggered, and since it didn't happen before, the tests are not written to expect it and now show unexpected output. Will need to update the tests (or drop the change).
```
	test/ninja/generated_sources_alias.py
	test/ninja/ninja_command_line.py
```

**Comment by mwichmann** [comment]
That's more interesting than I expected - looks like this is an internal action - it comes from the `Textfile` builder, and the comments in `SCons/Tool/ninja/NinjaState.py` make me think a different action name was expected. Here's one of the new warnings:
```
> scons: warning: Found unhandled function action '_action',  generating SCons command to build
> Note: this is less efficient than using Ninja. You can write your own ninja build generator for this function using NinjaRegisterFunctionHandler
> File "/home/mats/github/scons/scripts/scons.py", line 97, in <module>
```

**Comment by mwichmann** [comment]
Flagging this WIP/draft until some questions are answered.

**Comment by bdbaddog** [comment]
@mwichmann Is this still viable, or should it be closed?

**Comment by mwichmann** [comment]
> @mwichmann Is this still viable, or should it be closed?

Well, the state hasn't changed: ninja (mildly) misuses some stuff, and "fixing" it causes some tests to go awry, making the change a little bigger than I was up for at the time, with possibly no real benefit.  I can *possibly* be talking into dropping it, since I've never gone back to do the "further investigation".

**Comment by mwichmann** [comment]
I'll revisit this someday, no need to have it hanging around here for now.

**Pull request closed without merging**
