### PR TITLE
tools should not override existing path order

### PR DESCRIPTION
**Pull request by dmoody256**
This is a potential solution to https://github.com/SCons/scons/issues/3276.

This sets all tools to not delete existing paths, maintaining the original environment.

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Is there anywhere left in scons where delete_existing is defaulted?
Perhaps it makes more sense to change the default?
I can't imagine that the "normal" usage would want to move it to the end of a given path?

**Comment by dmoody256** [comment]
> Is there anywhere left in scons where delete_existing is defaulted?
> Perhaps it makes more sense to change the default?
> I can't imagine that the "normal" usage would want to move it to the end of a given path?

I made another to test that out PR #3281

**Comment by dmoody256** [comment]
I think I will close this PR in favor of changing the default and updating the test in #3281?

**Comment by bdbaddog** [comment]
O.k. Closing.

**Pull request closed without merging**
