### PR TITLE
Integrate `from __future__ import annotations`

### PR DESCRIPTION
**Pull request by Repiteo**
- Requires #4642

A conservative implementation of integrating `from __future__ import annotations` in the codebase. Updates all instances where type hints could utilize new syntax, utilizing newly added Ruff rules to find & adjust said instances. The resulting type-hints are much cleaner, even granting functionality which otherwise require 3.9 or 3.10 as their minimum Python version:
```python
# Before
def some_function(env: "SConsEnvironment") -> Optional[Tuple[List[str], Union[int, float]]]:

# After
def some_function(env: SConsEnvironment) -> tuple[list[str], int | float]] | None:
```
As a result of this new implementation, the hacky workarounds for forward-declaring types will no longer be necessary. Namely, `sctyping.py` is no longer necessary & has been removed. Instead, one should use `from typing import TYPE_CHECKING` & resolve imports like any other.

---
There's a more involved alternative of this PR that adds `from __future__ import annotations` as a required import instead, making it appear on **ALL** scripts in the codebase. While it's arguably a "better" option, it would also create *significantly* more noise in the changelog. If this approach were to be taken, it'd have to be part of a wider refactor.

## Contributor Checklist:

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `CHANGES.txt` and `RELEASE.txt` (and read the `README.rst`).
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Not sure we should ditch sctypes - be good to have a standard place for SCons-specific type combinations.  For example, a ton of environment methods take an argument that's either a pathname string, or a file node, or a list of pathname strings and/or file nodes.  That one is always going to be awkward to describe, even if we can stop using Union.

**Comment by mwichmann** [comment]
> Not sure we should ditch sctypes - be good to have a standard place for SCons-specific type combinations. For example, a ton of environment methods take an argument that's either a pathname string, or a file node, or a list of pathname strings and/or file nodes. That one is always going to be awkward to describe, even if we can stop using Union.

oops, I conflated sctypes and sctyping. never mind....

**Comment by mwichmann** [comment]
It's a pain that after years of requests, GitHub still doesn't support some form of stacked PRs.  I've tried some external solutions to this, and frankly, they were unusable for the kind of workflow SCons uses.

**Comment by mwichmann** [comment]
Looks good!

**Comment by bdbaddog** [comment]
Good work. Thanks!

**Comment by mwichmann** [comment]
This has actually caused a bunch of problems. The pipe-symbol-for-union changes are too early for Python 3.7-3.9:
```py
-        executor: Optional[ExecutorType] = None,
+        executor: Executor | None = None,
```

And the transition from uppercased type names to their actual names (`List` -> `list`) is too early for Python 3.7-3.8.  A test run with Python 3.7 is showing massive numbers of fails (1184 just now), raising the question of what we've done wrong with the CI, which should be catching this. We have at least one runner using a fairly old Python - we think.

**Comment by mwichmann** [comment]
Okay, I've removed the previous comment, my issue may have been an issue with some seriously out of skew environments and an experimental branch.  I'll bring it back if things reappear.

**Pull request merged**
