### PR TITLE
M4 test line endings change for windows

### PR DESCRIPTION
**Pull request by mwichmann**
Ugly fix for M4 test: when checking strings written for files, account
for line endings, was failing on Windows.  There should be something
cleaner coming but for now let's not keep failing the test.

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [X] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Okay, fine, it still doesn't work (error moved). Will revisit.

**Comment by bdbaddog** [comment]
Can you instead change the mym4.py to read and write bytes so sys.stdout doens't \n\r all the output?

**Comment by bdbaddog** [comment]
See these: 

https://stackoverflow.com/questions/908331/how-to-write-binary-data-in-stdout-in-python-3
https://stackoverflow.com/questions/32282448/read-stdin-as-binary

So something like this. Which may not work on py2. so may need a try/except or a different version for py3?
```
test.write('mym4.py', """
import sys
contents = sys.stdin.buffer.read()
sys.stdout.buffer.write(contents.replace('M4', 'mym4.py'))
sys.exit(0)
""")
```

**Comment by bdbaddog** [comment]
Fixed via another PR. Closing.

**Pull request closed without merging**
