### PR TITLE
Use pathlib in runtest

### PR DESCRIPTION
**Pull request by mwichmann**
In the past, there have been some mismatches between how tests are specified and how they are found.  testlist files, excludelist files and command-line specifications should be agnostic to operating system conventions. For example, typing `runtest.py foo/bar` on windows will produce paths like `foo/bar\test.py`, which is hard to match and painful to read, it should obviously match discovered `foo\bar\test.py`. Test information should be output using the native path separator for consistency.

Using pathlib lets these be normalized - stored in a common format and output in the expected format.

Adding this normalization of course broke some tests, which either intentionally or through omission expected some portion of a path to be UNIX-style. Specifically these five:

```
    test\runtest\baseline\fail.py
    test\runtest\baseline\no_result.py
    test\runtest\simple\fail.py
    test\runtest\simple\no_result.py
    test\runtest\simple\pass.py
    test\runtest\testargv.py
```

This was fixed and a general cleanup/reformat performed on the runtest tests.

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Does this pathsep change impact the failed_tests.log file? (Ideally not)

**Comment by mwichmann** [comment]
Things output about tests will be in "native" format - that's the information sent to the console, and the failed-tests log. Part of the motivations was that file sometimes had slashes going both ways, which I thought was a poor idea.

**Comment by bdbaddog** [comment]
So if it's `\` for failed_tests.log and you wanted to use same file to run on non-insane platform you'd be unable then..
Perhaps take the SCons approach and make all paths `/` separated?

**Comment by mwichmann** [comment]
If you use the file as input to a run, it works fine, as everything read from a testlist file, excludes file, or cli arguments is normalized as it's read in.

**Comment by mwichmann** [comment]
Added a testcase to hopefully assure the "foreign separator in a testlist" thing really works.

**Comment by bdbaddog** [comment]
RELEASE.txt blurb?

**Comment by mwichmann** [comment]
if needed. I don't usually do those if it's not user-visible (and not included in the wheel/sdist).

**Comment by bdbaddog** [comment]
RELEASE.txt has the `DEVELOPMENT` section for items like this.

**Pull request merged**
