### PR TITLE
Replace `black`/`flake8` with `ruff`

### PR DESCRIPTION
**Pull request by Repiteo**
After seeing that there's interest in reformatting the repo with `black` at some point, I wanted to propose [`ruff`](https://docs.astral.sh/ruff/) as an alternative instead. Recently the Godot repo changed over from `black` to this as our formatter, and it's an *absurd* speed upgrade. It doubles as a linter as well, so all relevant `flake8` settings were able to be migrated over; like before, it's an insane speed upgrade. Thanks to functioning as a drop-in replacement, no existing `#noqa` (or their equivalents) need to be changed in the codebase whatsoever, it just works™.

The settings in `pyproject.toml` are meant to be as 1-to-1 of a migration of the `black`/`flake8` settings as possible. The only exceptions were excluding rules that are redundant, such as flake8's `extend-ignore` not being necessary because `E3` is not enabled by default (would overlap with formatter). It'll be beneficial to adjust the rules/conditions prior to the future mega-format (particularly: removing `quote-style = "preserve"` & adding `extend-select = [I]`), but this makes for a rock-solid starting point.

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Have looked at using ruff.  It does - without looking at config settings - do something a little differently in check mode than I'm used to - but you seem to have caught that specific issue with the per-file-ignores emtry. I'm not averse to using ruff.

runtest.py doesn't need to be excluded - we'll want to clean it up too. Probably also *some* of the stuff in bin. (the doc production support). But that can always be poked at later.

I noticed also (after you corrected the entry so it actually works) that current mypy yells at our floor version of 3.6, since it only supports python.org supported Pythons - meaning 3.8 is going to go away pretty soon too. Not sure if we want to pin an old version of mypy. You've spotted that too, I see...

**Comment by mwichmann** [comment]
Oh, as an FYI, the `.flake8` file existed because we had a CI service called `sider` which ran checks on commits, so we could see that changes at least followed some kind of style, which was really nice.  But it was provided by a commercial company which decided to pivot to other things (non-free) so we lost that...  no settings in there are "holy", they were just an attempt to control `sider`'s noise level.

**Comment by bdbaddog** [comment]
How would we try ruff on our code with your changes in our own sandbox?

**Comment by mwichmann** [comment]
Just install `ruff` in a virtualenv and do `ruff check SCons`.

**Comment by bdbaddog** [comment]
Thanks for the PR!

**Pull request merged**
