### PR TITLE
Subst rewrite (for speed)

### PR DESCRIPTION
**Pull request by bdbaddog**
This is a work in progress of a rewrite of the Subst() functionality.
The current Subst implementation tends to burn 20-50% of non-build time.
This is largely due to two factors:
* A recursive explosion of calls
   * In one example with 16k nodes, Subst is getting called 1.6M times.
* Continually rerunning the same process on the same data
   * Given a string $SHOBJSUFFIX, it's parsed every single time it's evaluated.

The new implementation does a couple things differently:

1. Every time a value is set, it's parsed and tokenized
1. The recursion has been removed from Subst() evaluation.  The new algorithm is iterative.  This should be faster (Python is notoriously bad at recursive performance).  And theoretically allow pypy to hotspot better. 

The file src/engine/SCons/EnvironmentValues.md has notes about the implementation.  This is a work in progress so there will be updates as progress is made.

## Contributor Checklist:

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by acmorrow** [comment]
@bdbaddog - Can you provide some additional information on what currently works and what doesn't, and how to run SCons with the new feature fully enabled? I'm aware that some things don't currently work, but I'm curious to know if it might be possible to build some synthetic SCons workload that would require only the currently working parts, which might give some indication of the potential performance gains that could be realized. I think a separate comment detailing the current roadblocks to a complete implementation would be useful.

**Comment by bdbaddog** [comment]
It's not functional enough to use for any real builds at this point. As callables are not working. Let me see if I can instrument the unit tests to summarize what's working and not. That'd be better than manually doing it..

**Comment by grossag** [comment]
Did you end up getting anywhere with this change? I recently profiled SCons and found that Subst was very expensive.

**Comment by mwichmann** [comment]
I know it's getting time now and then in between other stuff @bdbaddog is working on.

Just musing... I'm wondering if there's a place to collect data from people who have profiled their work so that there's a way to determine if any prospective synthetic workload is actually representative of what people are seeing In Real Life (not everybody is mongodb after all!)

**Comment by bdbaddog** [comment]
> I know it's getting time now and then in between other stuff @bdbaddog is working on.
> 
> Just musing... I'm wondering if there's a place to collect data from people who have profiled their work so that there's a way to determine if any prospective synthetic workload is actually representative of what people are seeing In Real Life (not everybody is mongodb after all!)

All benchmarking ever done on SCons indicates subst is always a large percent of runtime (non counting running external commands and heavyweight user built python actions/builders).

**Comment by bdbaddog** [comment]
> Did you end up getting anywhere with this change? I recently profiled SCons and found that Subst was very expensive.

It's still a WIP..

**Comment by bdbaddog** [comment]
Closing this for now. 
When (if) work restarts I'll float a new PR.

**Pull request closed without merging**
