### PR TITLE
fix CheckFunc detection code for MSVC

### PR DESCRIPTION
**Pull request by jw0k**
This patch fixes detection of some functions on Visual 2019 with optimizations (`/O2`) enabled.

For example: `memmove` is incorrectly detected as not available on Visual 2019 with `/O2` enabled because `/O2` enables `/Oi` which replaces `memmove` with a compiler intrinsic, which in turn causes the test code fail to compile. The `#pragma function` prevents replacing the tested function with a compiler intrinsic.

### CODE REVIEW

**Comment by bdbaddog** [comment]
Can you add a CheckFunc('memmove') to test/Configure/config-h.py test, also add a blurb to src/CHANGES.txt to describe what you fixed.

**Comment by jw0k** [comment]
@bdbaddog Done.

**Comment by bdbaddog** [comment]
@jw0k - Pending completion of CI builds. Looks good to me. I'll merge once they're done, unless there's a surprise. Thanks for the good work!

**Comment by bdbaddog** [comment]
Merging. No test failures caused by this change.

**Comment by jw0k** [comment]
@bdbaddog Thank you.

**Pull request merged**
