### PR TITLE
Replace usage of unittest.TestSuite with unittest.main()

### PR DESCRIPTION
**Pull request by swuecho**
fix the easy ones follow the instruction in #3113.

the tests below have warning like
```
./home/hwu/dev/scons/src/engine/SCons/dblite.py:117: ResourceWarning: unclosed file <_io.BufferedWriter name='.sconsign.dblite'>
  self._open(self._file_name, "wb", self._mode)
/home/hwu/dev/scons/src/engine/SCons/dblite.py:206: ResourceWarning: unclosed file <_io.BufferedReader name='.sconsign.dblite'>
  return dblite(file, flag, mode)


ERROR: test_basic (__main__.cppAllTestCase)
Test basic #include scanning
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/engine/SCons/cppTests.py", line 431, in setUp
    self.cpp = self.cpp_class(current = ".",
AttributeError: 'cppAllTestCase' object has no attribute 'cpp_class'

======================================================================
ERROR: test_expression (__main__.cppAllTestCase)
Test #if with arithmetic expressions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "src/engine/SCons/cppTests.py", line 431, in setUp
    self.cpp = self.cpp_class(current = ".",
AttributeError: 'cppAllTestCase' object has no attribute 'cpp_class'
```

```
Scanner/CTests.py
463:    TestUnit.run(suite())

Scanner/ScannerTests.py
628:    TestUnit.run(suite())

Scanner/FortranTests.py
536:    TestUnit.run(suite())

Scanner/IDLTests.py
448:    TestUnit.run(suite())

Tool/ToolTests.py
83:    TestUnit.run(suite)

EnvironmentTests.py
3982:    TestUnit.run(suite)

Node/FSTests.py
3781:    TestUnit.run(suite)

PathListTests.py
201:    TestUnit.run(suite)

BuilderTests.py
1645:    TestUnit.run(suite)

cppTests.py
741:    TestUnit.run(suite)

SConsignTests.py
396:    TestUnit.run(suite)
```

I'd like to get the easy ones fixed in batch and deal with the remaining one by one.

### CODE REVIEW

**Comment by swuecho** [comment]
https://github.com/SCons/scons/blob/932c577395cf646a82581afeb9fd1c9faf4d4999/src/engine/SCons/dblite.py#L117

not sure what is does here, but will throw waring

```
hwu@Work:~/dev/scons$ PYTHONPATH=$PWD/QMTest:$PWD/src/engine:$PWD/testing/framework python src/engine/SCons/SConsignTests.py 
../home/hwu/dev/scons/src/engine/SCons/dblite.py:117: ResourceWarning: unclosed file <_io.BufferedWriter name='.sconsign.dblite'>
  self._open(self._file_name, "wb", self._mode)
/home/hwu/dev/scons/src/engine/SCons/dblite.py:206: ResourceWarning: unclosed file <_io.BufferedReader name='.sconsign.dblite'>
  return dblite(file, flag, mode)
....
```

**Comment by bdbaddog** [comment]
If I remember correctly these warnings only show up with py 3.6 and 3.7 ?

**Comment by bdbaddog** [comment]
Did you verify in each case that the # of tests run didn't change before/after the change?

**Comment by swuecho** [comment]
@bdbaddog  Yes, the resource warning is enabled in recent python version.  not sure why the old way to organize test did not trigger any of this warning. 

I run each test before make any change. can not remember any that the # of test changes.

I check the # of total test before  https://travis-ci.org/SCons/scons/jobs/403191088. is 1174, which is the same after my change.

**Pull request merged**
