### PR TITLE
Enable use of target and source in generators in CPPDEFINES

### LINKED ISSUE #3790: The target and source variables are not usable for generators in CPPDEFINES
**Describe the bug**
If `CPPDEFINES` contains a generator, that generator is called, but with empty `target` and `source` variables.

**Required information**
* Link to SCons Users thread discussing your issue.
Discussed on Discord devel channel

* Version of SCons
3.1.2

* Version of Python
3.7

* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
N/A

* How you installed SCons
Vendored

* What Platform are you on? (Linux/Windows and which version)
macOS

* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
```python
env = Environment()

def define_generator(target, source, env, for_signature):
    print('XXX', [str(t) for t in target], [str(s) for s in source])
    return "DEFINE"
env['DEFINE_GENERATOR'] = define_generator

env.Program(
    target='main',
    source='main.c',
    CPPDEFINES='$DEFINE_GENERATOR'
)
```

Will print

```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
XXX [] []
XXX [] []
scons: *** [main.o] Source `main.c' not found, needed by target `main.o'.
scons: building terminated because of errors.
```

Those `XXX` things should contain the target and source lists.

A fix is pretty easy, in case I don't get to a PR:

```python
diff --git a/src/third_party/scons-3.1.2/scons-local-3.1.2/SCons/Defaults.py b/src/third_party/scons-3.1.2/scons-local-3.1.2/SCons/Defaults.py
index c39c417647..118356d1b5 100644
--- a/src/third_party/scons-3.1.2/scons-local-3.1.2/SCons/Defaults.py
+++ b/src/third_party/scons-3.1.2/scons-local-3.1.2/SCons/Defaults.py
@@ -492,12 +492,12 @@ def processDefines(defs):
     return l


-def _defines(prefix, defs, suffix, env, c=_concat_ixes):
+def _defines(prefix, defs, suffix, env, target, source, c=_concat_ixes):
     """A wrapper around _concat_ixes that turns a list or string
     into a list of C preprocessor command-line definitions.
     """

-    return c(prefix, env.subst_path(processDefines(defs)), suffix, env)
+    return c(prefix, env.subst_path(processDefines(defs), target=target, source=source), suffix, env)


 class NullCmdGenerator(object):
@@ -574,7 +574,7 @@ ConstructionEnvironment = {
     '_LIBFLAGS'     : '${_concat(LIBLINKPREFIX, LIBS, LIBLINKSUFFIX, __env__)}',
     '_LIBDIRFLAGS'  : '$( ${_concat(LIBDIRPREFIX, LIBPATH, LIBDIRSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
     '_CPPINCFLAGS'  : '$( ${_concat(INCPREFIX, CPPPATH, INCSUFFIX, __env__, RDirs, TARGET, SOURCE)} $)',
-    '_CPPDEFFLAGS'  : '${_defines(CPPDEFPREFIX, CPPDEFINES, CPPDEFSUFFIX, __env__)}',
+    '_CPPDEFFLAGS'  : '${_defines(CPPDEFPREFIX, CPPDEFINES, CPPDEFSUFFIX, __env__, TARGET, SOURCE)}',

     '__libversionflags'      : __libversionflags,
     '__SHLIBVERSIONFLAGS'    : '${__libversionflags(__env__,"SHLIBVERSION","_SHLIBVERSIONFLAGS")}',
```

* How you invoke scons (The command line you're using "scons --flags some_arguments")

### PR DESCRIPTION
**Pull request by acmorrow**
Fixes #3790 

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `CHANGES.txt` (and read the `README.rst`)
* [N/A] I have updated the appropriate documentation

I'll add a note to README once this is agreed on.

### CODE REVIEW

**Comment by acmorrow** [comment]
This should fix #3790

**Comment by mwichmann** [comment]
looking reasonable to me.

**Comment by bdbaddog** [comment]
Needs a blurb in CHANGES.txt and RELEASE.txt

**Comment by acmorrow** [comment]
> Needs a blurb in CHANGES.txt and RELEASE.txt

Sure, coming right up.

**Comment by acmorrow** [comment]
@bdbaddog - Done

**Comment by bdbaddog** [comment]
Linked issue to this PR.
Looks good .
Merging.

**Pull request merged**
