### PR TITLE
Add method for individual tools to search for windows install paths which aren't in SCons' defaults + changes to get more tests to pass on windows and/or appveyor

### PR DESCRIPTION
**Pull request by bdbaddog**
Add method for individual tools to search for windows install paths which aren't in SCons' defaults.

- Updated logic for mingw and clang on win32 to search default tool install paths if not
      found in normal SCons PATH.  If the user specifies PATH or tool specific paths they
       will be used and the default paths below will be ignored.
    - Default path for clang/clangxx : C:\Program Files\LLVM\bin
    - Default path for mingw         : c:\MinGW\bin

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by dmoody256** [comment]
mingw binaries can also be installed in cygwins paths such as:

- C:\cygwin64\bin
- C:\msys64
- C:\cygwin\bin
- C:\msys

So maybe add those to the list of default paths to find mingw binaries.

**Comment by bdbaddog** [comment]
Apparently clang also requires a msvc or msvs tool configured, or also perhaps mingw so that it can find header files via INCLUDE shell environment variable. So my fixes in this patch for clang are not sufficient.

**Comment by bdbaddog** [comment]
For clang include path initialization look at : https://github.com/llvm-mirror/clang/blob/master/lib/Driver/ToolChains/MSVC.cpp

**Comment by dmoody256** [comment]
There is a Mircosoft implementation of clang which takes MSVC compiler style flags (forward slash) which is different than the mingw clang which is like gcc style flags (dash). 

_Sent from my Galaxy Note5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bdbaddog** [comment]
Any idea how to detect which is which?

**Comment by dmoody256** [comment]
The MSVC one is named clang-cl, more info here:
https://clang.llvm.org/docs/UsersManual.html#clang-cl

**Comment by dmoody256** [comment]
Yeah, did you see the PR I did on this branch in your fork?

**Comment by bdbaddog** [comment]
Didn't see it until now.
Ugh.. Github doesn't make you automatically watch your on repos?

Anyway see comments there..

**Comment by dmoody256** [comment]
Opened https://github.com/bdbaddog/scons/pull/2 for this branch in your repo @bdbaddog

**Comment by bdbaddog** [comment]
Merging.

**Pull request merged**
