### PR TITLE
Debug option "timestamp"

### PR DESCRIPTION
**Pull request by edobez**
Added debug option _timestamp_, which extends `--debug=time` output with the absolute start and end time for each build command.
Selecting this option implicitly enables `--debug=time`.

The reason for adding this feature is to have a more detailed output of the build commands. This is useful to profile parallel builds and compute effective CPU utilization while building.

The test for this feature is a copy of the test for `--debug=time`, plus some additional checks.
I didn't remove the common tests, since enabling option `--debug=timestamp` also enables option `--debug=time`.

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [X] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
I would probably pick a different name for the option, since "timestamp" already has a rather specific meaning to scons, namely to use file modification times in the decider algorithm. I feel like calling this feature "timestamp" also could be a bit confusing.

**Comment by bdbaddog** [comment]
time_commands?

**Comment by bdbaddog** [comment]
action_timestamps ?

**Comment by edobez** [comment]
action_timestamps could be fine. Something more specific like `target_timestamps`?
Maybe I am missing some terminology here. What is the relation between `actions` and `targets`?

**Comment by bdbaddog** [comment]
@edobez - A builder may have many targets, But one Action (which can have multiple steps) which would be wrapped by the new timestamps

**Comment by edobez** [comment]
Makes sense. I changed the option from "timestamp" to "action_timestamps".

**Comment by bdbaddog** [comment]
Nicely written test.
One minor nit. We're trying to encourage new tests be written as fixtures (the logic doesn't write the test files) any chance you can modify to work that way?

See:
https://github.com/SCons/scons/wiki/TestingMethodology#working-with-fixtures

**Comment by edobez** [comment]
Actually most of the test is copied from `debug-time.py` :-D
Since this option includes the option --debug=time implicitly, I'm not even sure if the repetition of the test is needed. I would rather only add the check on the presence of the timestamps and if their value has sense.

**Comment by bdbaddog** [comment]
Merging.

**Pull request merged**
