### PR TITLE
[WIP] Rust support

### PR DESCRIPTION
**Pull request by Liorst4**
# Add support for the rustc compiler.

I'm adding rust support to scons.
My goal is to add the ability to convert c/cxx projects using scons to rust, by converting one module (obj) at a time.

## Tasks
* [x] Add rustc
* [x] Detect rustc
* [x] Omit obj files from the rust compiler.
* [x] Add support for compilation flags
* [x] Create a crate method
* [x] Add the rust standard library to the library path
* [ ] Add a scanner for rust
* [ ] Add more tests
* [ ] Add documentation
* [ ] Handle the main function (In rust there is a difference between a `bin` crate and a `lib` crate)
* [ ] Run rust tests (`#[test]` in the `.rs` files)

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Looks like your test is failing in all CI.
 (appveyor and travis-ci)

Also you may want to update the CI config files to install rust
```
.travis.yml
.appveyor.yml
.travis/install.sh
```

**Comment by bdbaddog** [comment]
@Liorst4 - any more development on this to push?

**Comment by Liorst4** [comment]
> @Liorst4 - any more development on this to push?

Not in the foreseeable future

**Comment by bdbaddog** [comment]
@Liorst4 - I've tagged this PR as "rust" and I'll close it for now. If you get some time to move it forward, you should be able to just re-open it.
Thanks for the work you've done thus far.

**Pull request closed without merging**
