### PR TITLE
Add some cheap return and parameter annotations

### PR DESCRIPTION
**Pull request by mwichmann**
Use: https://github.com/JelleZijlstra/autotyping to add "safe" return annotations.

Where a parameter has a default value that is an obvious scalar type (`bool`, `int`, `str`, etc.) add those annotations as well.

Also fixed two small bugs that popped up when sanity-checking with mypy.  One in FortranCommon, where a return had been previously annotated to be a tuple of `Action`, which should be `ActionBase` - `Action` is the factory function, not the base class. The other was a typo in the error raised in `_add_cppdefines` - the message was formatted with the value of `define` which should have been `defines`.

This does not change SCons behavior (typing still only consumed by external tools), so no doc/test impact.

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by jcbrill** [comment]
@mwichmann Any chance you could give the full command-line option specifications that were used to invoke autotyping to generate the type annotations?

If there are any installation and configuration hints, that would be helpful as well.

All existing PRs that predate this commit may have additional functions that will not have any of the additional type annotations.  I'm interested in a (low energy) method to check if additional annotations are necessary in my own outstanding PRs.

**Comment by mwichmann** [comment]
The super-short summary is to install (with pip) the package `autotyping` and first run it like this in the worktree:
```
python -m libcst.tool codemod autotyping.AutotypeCommand --safe SCons
```
Then, if you like, rerun it replacing `--safe` with `--bool-param --int-param --float-param --str-param --bytes-param` to also do the *parameters whose types can be easily deduced because they have a scalar-type default*, which is less guaranteed to be "safe" since code could be misbehaving and assigning something that doesn't match the type of the default.

There's setup information in more detail at https://github.com/JelleZijlstra/autotyping (you do need to setup the toml file, and it works to just copy the one from the autotype project, as it describes)

**Comment by mwichmann** [comment]
> The super-short summary is to install (with pip) the package `autotyping` and first run it like this in the worktree:
> 
> ```
> python -m libcst.tool codemod autotyping.AutotypeCommand --safe SCons
> ```
> 
> Then, if you like, rerun it replacing `--safe` with `--bool-param --int-param --float-param --str-param --bytes-param` to also do the _parameters whose types can be easily deduced because they have a scalar-type default_, which is less guaranteed to be "safe" since code could be misbehaving and assigning something that doesn't match the type of the default.
> 
> There's setup information in more detail at https://github.com/JelleZijlstra/autotyping (you do need to setup the toml file, and it works to just copy the one from the autotype project, as it describes)

Oops, I forgot I made a local mod to the config file, by default this setup runs black on everything, and we're not ready for that.  So my config file (which is a yaml, not a toml, too many markup languages out there!) looks like:
```py
# String that LibCST should look for in code which indicates that the
# module is generated code.
generated_code_marker: '@generated'
# Command line and arguments for invoking a code formatter. Anything
# specified here must be capable of taking code via stdin and returning
# formatted code via stdout.
#formatter: ['black', '-']
formatter: ['cat', '-']
# List of regex patterns which LibCST will evaluate against filenames to
# determine if the module should be touched.
blacklist_patterns: [r'*Tests.py']
# List of modules that contain codemods inside of them.
modules:
- 'libcst.codemod.commands'
- 'autotyping'
# Absolute or relative path of the repository root, used for providing
# full-repo metadata. Relative paths should be specified with this file
# location as the base.
repo_root: '.'
```

**Comment by jcbrill** [comment]
@mwichmann THANKS for the help.

**Pull request merged**
