### PR TITLE
Switch travis-ci 3.9 to released + 20.04

### PR DESCRIPTION
**Pull request by mwichmann**
Reconfigure the CI setup to build using released 3.9, and the latest Ubuntu LTS, so both are represented.  Does not add 3.10-dev, still need to think about whether we can make the Travis build bigger, or if a separate refactor needs to happen.

Dropped the doc/package build, since that is now done in a GitHub Action.

A side effect of making the tests pass on 20.04 was that the ldc compiler is now installed a different way (using the recommended snap installation instead of unpacking a downloaded tarball) is that an additional path had to be added - `/snap/bin`.

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [X] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Tried to switch the install of ldc2 to a snap, which works great. For Ubuntu. But SCons doesn't have knowledge of snaps as it crafts its own idea of path for finding utilities, so it finds no ldc compiler.  This is an old familiar irritant with SCons, subject of a FAQ and all. I can add `/snap/bin` to `PATH` in `Platform/posix.py` and things go back to looking normal - except there's still a gdc test failing (note I didn't do anything to fiddle with gdc installation!), only in the 3.9/20.04 combo: maybe this is a change in gdc as picked up by 20.04, it's now from the 10.x GNU compiler collection, the test doesn't give any output when failing, but it's a special case looking for a failure condition, maybe that's not a fail any longer?  

Question: why do even simple changes open up cans of worms?

Is it okay to add `/snap/bin`?

**Comment by mwichmann** [comment]
Grrr, looks like the dmd error message has switched from "unrecognized command line option" to "unrecognized command-line option" - it grew a dash. I guess since it's a regex pattern I can just wildcard it.

**Comment by mwichmann** [comment]
hmm, looks like it didn't run tests this update?

**Comment by bdbaddog** [comment]
Please add a snippet RELEASE.txt that we're adding /snap/bin to default PATH SCons uses for posix systems.

**Pull request merged**
