### PR TITLE
Add SConstruct.py to the search list

### PR DESCRIPTION
**Pull request by Hecatron**
This is a small change to allow scons to pick up on SConstruct.py if SConstruct isn't found
in relation to https://github.com/SCons/scons/issues/3039

At the moment to get debugging to work within Visual Studio I have to create a dummy SConstruct file within the following in
```
exec(compile(open('SConstruct.py').read(), 'SConstruct.py', 'exec'))
```
Then have the real code located within SConstruct.py
This is because Visual Studio doesn't recognize the code within the file as python due to the lack of a file extension. This just makes life a little bit easier.
SConscript files within sub-directories are fine since you need to specify those with a file path within the script sitting above anyway.

### CODE REVIEW

**Comment by bdbaddog** [comment]
Can you add a test? An likely will need an update to at least the manpage.

**Comment by Hecatron** [comment]
I can if you want, I wasn't sure if it'd need one

**Comment by bdbaddog** [comment]
To be consistent with the SConstruct filenaming options can you also add sconstruct.py (all lower)

**Comment by Hecatron** [comment]
If using the .py extension is a problem (if your worried about folks trying to run it directly)
then we could use something else like SConstript.scons as long as it's possible to use a file with an extension then it should possible to set the IDE to interpret it as a python file

**Comment by bdbaddog** [comment]
.py is fine. We've had similar requests before.
If you can add the lowercase to be consistant and update the changed docs, and add a simple test, we should be good to merge.

**Comment by Hecatron** [comment]
those changes should now already be in (for lowercase / to the docs / tests etc)
the new search order is now ['SConstruct', 'Sconstruct', 'sconstruct', 'SConstruct.py', 'sconstruct.py']
the last 2 are the ones I've added in, if you also want Sconstruct.py let me know and I'll add that in as well

**Comment by bdbaddog** [comment]
May as well be consistant. Please go ahead and add Sconstruct.py.
Thanks!

**Comment by Hecatron** [comment]
Okay now done

**Pull request merged**
