### PR TITLE
User Guide: Add mention of `no_progress` option when user passes -Q

### PR DESCRIPTION
**Pull request by ghost**
Accordingly to [changes to 4.0.0](https://scons.org/scons-400-is-available.html)

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `CHANGES.txt` and `RELEASE.txt` (and read the `README.rst`).
* [x] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Sigh... that's the problem with maintaining similar information in multiple places.  At a glance, it looks like other rows are missing from the table in the User Guide compared to the manpage.

**Comment by mwichmann** [comment]
30 rows in the user guide table, 41 in the manpage `GetOption` table, 19 in the manpage `SetOption` table (of course, not all the options are "settable"). 

@bdbaddog - is it better to point to the `GetOption/SetOption` entries here than try to duplicate?

**Comment by mwichmann** [comment]
Should we update this to say something like "Get/Set Option table out of date compared to manpgage"?

**Comment by bdbaddog** [comment]
@mwichmann - is there anyway we can single source this table? Stick in a file and include both places?

**Comment by mwichmann** [comment]
not that easy with current setup, though possible, I think.

**Pull request merged**
