### PR TITLE
Temp file munge cmd line print

### PR DESCRIPTION
**Pull request by dmoody256**
TempFileMunge was ignoring my PRINT_CMD_LINE_FUNC and just printing all over my build output

### CODE REVIEW

**Comment by bdbaddog** [comment]
There's a couple test failures. Can you investigate?

**Comment by dmoody256** [comment]
yeah, looks like it related to python 2.7, my local environment is py3 so I didn't see it. I think it related to py3 class inheritance.

**Comment by bdbaddog** [comment]
Are you able to try with py2.7 and fix?

**Comment by bdbaddog** [comment]
Looks like you dropped your changes to src/CHANGES.txt

**Comment by dmoody256** [comment]
update to CHANGES.txt was in a different commit: https://github.com/SCons/scons/pull/3260/commits/53c892c123ac9ea3d4f1cdb3e5e0e1887e8c73a4

It's in the full changeset for this PR

**Pull request merged**
