### PR TITLE
Speedup bin/docs-update-generated.py by caching parsed docbook schema

### PR DESCRIPTION
**Pull request by bdbaddog**
Speedup bin/docs-update-generated.py by caching parsed docbook schema.

Yields approx 60x speedup

# Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `src/CHANGES.txt` (and read the `README.txt` in that directory)
* [X] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
It feels a little awkward but Im not seeing a problem... and this isn't scons itself, so if it works it's okay, no?

**Comment by bdbaddog** [comment]
@mwichmann - right. Just wanted some other eyes to make sure this is a valid change. As far as I can tell from the docs, there's no need to reload the schema for each file you validate against.  Hoping @dirkbaechle will have a chance to review as this is initially his creation.

**Comment by mwichmann** [comment]
`validate_all_xml` calls the `validateXml` function in a loop, so it's always the same.

**Comment by bdbaddog** [comment]
@dirkbaechle - I'm going to merge this. But please add any notes if you think this change is incorrect?

**Pull request merged**
