### PR TITLE
Replace `int main()` with `int main(void)` in `CheckLib()`

### LINKED ISSUE #4373: Configure.CheckLib() error with -Wstrict-prototypes
This is a continuation of #3095. As noted in [this comment](https://github.com/SCons/scons/pull/3096/files#r1257532304), there was one more instance that was missed in PR #3096:

https://github.com/SCons/scons/blob/810ca6c8895b01cbd636d83079f6a848dc36adf6/SCons/Conftest.py#L677-L684

### PR DESCRIPTION
**Pull request by JonathonReinhart**
This fixes another instance missed in #3096.

Fixes #4373

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
  * N/A: See https://github.com/SCons/scons/pull/3096#issuecomment-364804847
* [x] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation
  * N/A

### CODE REVIEW

**Comment by JonathonReinhart** [comment]
I tested this locally and it fixed my configure tests which were broken due to the failed compilation.

**Comment by mwichmann** [comment]
Looks like this isn't passing the CI test suite, with `test/Configure/ConfigureDryRunError.py` failing. Haven't had time to hunt it down yet.

**Comment by mwichmann** [comment]
Grrr, irritating test. It's not really failing, it's that there are built-in expected filenames for this test (using hashes of the contents, in line with a new "uniquing" strategy) which we now have to recompute since a test file changed:
```py
# depending on which default hash function we're using, we'd expect one of the following filenames.
# The filenames are generated by the conftest changes in #3543 : https://github.com/SCons/scons/pull/3543/files
possible_filenames = {                                                         
    'md5': "conftest_df286a1d2f67e69d030b4eff75ca7e12_0.c",                    
    'sha1': "conftest_6e784ac3248d146c68396335df2f9428d78c1d24_0.c",           
    'sha256': "conftest_be4b3c1d600e20dfc3e8d98748cd8193c850331643466d800ef8a4229a5be410_0.c"
}
```

**Comment by mwichmann** [comment]
and... there aren't really instructions for how to do this. I ended up doing a non-dry-run test of `conf.CheckLib('m')`, then looking in the `.sconf_temp` directory created, finding the `.c` file, and manually running `md5sum`, `sha1sum`, and `sha256sum` on it. Of course, my system, having not been set up in any special way, had already generated the file with the md5sum, so I didn't really need to repeat that, it was just a cross-check.  This looks to be the new filename dict contents needed for the test:
```py
possible_filenames = {                                                         
    'md5': 'conftest_e492448966d6e04631c094ba6d6e8a32_0.c',                    
    'sha1': 'conftest_f0a9e7fe48f48687797dbafb5d07071d35f86dd2_0.c',           
    'sha256': 'conftest_e856bf0bdb229b16823f193eee68254b885340d0b2f0277ff2eaca78aa0ba7aa_0.c',
} 
```

Just a *little* bit fragile, this...

**Comment by mwichmann** [comment]
sumitted a PR to the PR, which I hopefully got right.

**Comment by bdbaddog** [comment]
> and... there aren't really instructions for how to do this. I ended up doing a non-dry-run test of `conf.CheckLib('m')`, then looking in the `.sconf_temp` directory created, finding the `.c` file, and manually running `md5sum`, `sha1sum`, and `sha256sum` on it. Of course, my system, having not been set up in any special way, had already generated the file with the md5sum, so I didn't really need to repeat that, it was just a cross-check. This looks to be the new filename dict contents needed for the test:
> 
> ```python
> possible_filenames = {                                                         
>     'md5': 'conftest_e492448966d6e04631c094ba6d6e8a32_0.c',                    
>     'sha1': 'conftest_f0a9e7fe48f48687797dbafb5d07071d35f86dd2_0.c',           
>     'sha256': 'conftest_e856bf0bdb229b16823f193eee68254b885340d0b2f0277ff2eaca78aa0ba7aa_0.c',
> } 
> ```
> 
> Just a _little_ bit fragile, this...

Here's how I usually rerun to recompute such
`PRESERVE=1 python runtest.py <the test>`

Then cd or ls into that dir looking for the files.. messy, but not too complicated?

**Comment by mwichmann** [comment]
> Here's how I usually rerun to recompute such `PRESERVE=1 python runtest.py <the test>`
> 
> Then cd or ls into that dir looking for the files.. messy, but not too complicated?

Ah... but this one isn't "usually". I tried that, but this test is that you get the expected message if you try to Configure in dry-run mode.  Where the test program is never generated - which is in fact what the error message we're looking for is telling us.

**Comment by bdbaddog** [comment]
> > Here's how I usually rerun to recompute such `PRESERVE=1 python runtest.py <the test>`
> > Then cd or ls into that dir looking for the files.. messy, but not too complicated?
> 
> Ah... but this one isn't "usually". I tried that, but this test is that you get the expected message if you try to Configure in dry-run mode. Where the test program is never generated - which is in fact what the error message we're looking for is telling us.

OIC... you need the file names which aren't created.. Fun.. ;)
Use the PRESERVE=1 and then cd into that dir and run without dry-run?

**Comment by mwichmann** [comment]
Yeah, maybe.  It was just a three-liner to write a new SConstruct once I figured what was going on.  Wonder if the test ought to actually try all three filenames (by running again in sha1 and sha256 mode).  Maybe for a different PR?

**Comment by JonathonReinhart** [comment]
Thanks @mwichmann and @bdbaddog for quickly following up and implementing 567c32add14cc14d146f3732c7cab4b5dcdc8f9f to get this merged!

**Pull request merged**
