### PR TITLE
Set Tasks class as abstract

### PR DESCRIPTION
**Pull request by mwichmann**
`needs_execute` method set as an abstract method, meaning you can't instantiate `Task` itself, and derived classes must implement the method.  The former warning framework for this (deprecated) is
disabled, and some unit tests that were not implementing `needs_execute` were fixed - by deriving from the `AlwaysTask` class.

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [X] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Is there a test which verifies that using the needs_execute from abstract class fails?

**Comment by mwichmann** [comment]
There was: `TaskmasterTests.py` :)  I fixed that, because it wasn't really appropriate to leave a failed unittest.  But I guess I could resurrect that into an expected-fail test if needed?

**Comment by bdbaddog** [comment]
Yes. I think the change basically now expects if you use Task and don't implement needs_execute, it should raise an exception? So a test for that failure would verify it's working as expected. and if say a bad merge happened it would fail if it no longer failed as expected

**Comment by mwichmann** [comment]
Yes, it looks like: 
```
Traceback (most recent call last):
  File "SCons/TaskmasterTests.py", line 313, in test_next_task
    t = tm.next_task()
  File "/home/mats/github/scons/SCons/Taskmaster.py", line 968, in next_task
    task = self.tasker(self, tlist, node in self.original_top, node)
TypeError: Can't instantiate abstract class MyTask with abstract methods needs_execute
```

So I just have to figure out how to set up this kind of negative test.

**Comment by bdbaddog** [comment]
Wrap a call in a Try/Except/else have the else set failing bool variable to True. Then self.Assert(did_it_fail, "... ")?

**Comment by mwichmann** [comment]
there's support for it, it's just I've never used it.  unittest defines an `assertRaises` method.

**Comment by mwichmann** [comment]
Hmmm, sider is grumpy because I call something which causes the class to instantiate, and don't do anything with it because we only care it raised an exception.  Need to fix?

**Comment by bdbaddog** [comment]
what happens if you just do task.next_task() and don't assign it to a value? and/or _ = ?

**Comment by mwichmann** [comment]
yes, that would quiet sider.  I'll do this eventually, or you could just jump the queue - the underscore should work fine.

**Pull request merged**
