### PR TITLE
Changes to support Fortran submodules, as implemented by Intel and Gn…

### PR DESCRIPTION
**Pull request by nDimensionalSpace**
…u compilers

## Contributor Checklist:

* [ X ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ X ] I have updated `CHANGES.txt` (and read the `README.rst`)
* [N/A] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Did you mean to PR this to @pdiener 's repo?

**Comment by nDimensionalSpace** [comment]
Uhhhh, yes, I did . . .  Indeed, that is what I did.  Idk why you would have seen it.

**Comment by bdbaddog** [comment]
Nope.You PR'd to SCons/master and not his repo.

**Comment by nDimensionalSpace** [comment]
Interesting.  The attached screenshot shows the browser screen that I launched the PR from, including the target of the “Pull request” link in the lower left.  Not sure how it got directed to the main repo . . .  Regardless, happy to proceed however, like, kill this and start over, or whatever.  But if that’s the case, let me know how to submit in a way that won’t do the same thing again.

**Comment by nDimensionalSpace** [comment]
Any further thoughts re: how to proceed with this?

**Comment by bdbaddog** [comment]
> Any further thoughts re: how to proceed with this?
> […](#)
> On Aug 18, 2020, at 6:13 PM, Neil Hodge ***@***.***> wrote: Interesting. The attached screenshot shows the browser screen that I launched the PR from, including the target of the “Pull request” link in the lower left. Not sure how it got directed to the main repo . . . Regardless, happy to proceed however, like, kill this and start over, or whatever. But if that’s the case, let me know how to submit in a way that won’t do the same thing again. <Screen Shot 2020-08-18 at 6.09.21 PM.png> > On Aug 18, 2020, at 6:03 PM, William Deegan ***@***.***> wrote: > > > Nope.You PR'd to SCons/master and not his repo. > > — > You are receiving this because you authored the thread. > Reply to this email directly, view it on GitHub, or unsubscribe. >

@rsf83F4qW26jC6MVqBVC - grab me when you're next on discord and we'll see if we can get it sorted. I'd guess. you branched of upstream/master and not from @pdiener 's branch..

**Comment by bdbaddog** [comment]
Also.. no screenshot is attached..

**Pull request closed without merging**
