### PR TITLE
check for SONAME and generate symlinks (github Issue #3246)

### PR DESCRIPTION
**Pull request by dmoody256**
added check for SONAME and generate soname from that in link tools

this should resolve Issue #3246.

I also did some slight testing on the updated test on osx through Travis, below is a log:
https://travis-ci.org/github/dmoody256/scons/jobs/682044422

## Contributor Checklist:

* [x] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `src/CHANGES.txt` (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by dmoody256** [comment]
Looking at the codecov patch coverage, it looks like the applelink tool does get tested even though I don't think we have any CI running tests on OSX. I assume there is some other method performed on Travis Linux or Appveyor Windows to test applelink in those environments? Anyone know what test is testing applelink on Linux/Windows? 

I tested these changes on actual osx in some temporary .travis.yml changes, but if there is another test I can update that would be great to put in the regular CI.

**Comment by dmoody256** [comment]
> Anyone know what test is testing applelink on Linux/Windows?

nevermind, name of the test made it pretty obvious

**Comment by bdbaddog** [comment]
> > Anyone know what test is testing applelink on Linux/Windows?
> 
> nevermind, name of the test made it pretty obvious

Indeed many tests will mock out the tool if they're not available where it makes sense and  the logic around the tool can be tested on any platform.

**Comment by dmoody256** [comment]
CI failures don't seem related to these changes, Appveyor failed interactive.py test (known intermittent failure) and then Travis failed test/Dir/source.py only for 3.8, but not in my travis run of the same commit: https://travis-ci.org/github/dmoody256/scons/builds/682199925

I think this PR is ready to go.

**Comment by bdbaddog** [comment]
Rerunning failed travis build.  That's not a common intermittent failure. (Still wouldn't expect it to come from this change).

**Comment by bdbaddog** [comment]
@acmorrow  - does this resolve #3246  for you?

**Pull request merged**
