### PR TITLE
Parallel cache push strawman

### PR DESCRIPTION
**Pull request by acmorrow**
## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by acmorrow** [comment]
@bdbaddog - This seems to pass all tests, but please let me know if you would prefer to do this under a `--experimental=???` flag and I can rework it like that.

**Comment by bdbaddog** [comment]
One concern/question.
Previously the node had `.cached` which you could use to see if the file was cached or not.
Now there's only a check to see if it shouldn't be cached, but no way to tell if the node has actually been cached?

Would restoring .cached break anything in this change?

**Comment by acmorrow** [comment]
> One concern/question. Previously the node had `.cached` which you could use to see if the file was cached or not. Now there's only a check to see if it shouldn't be cached, but no way to tell if the node has actually been cached?
> 
> Would restoring .cached break anything in this change?

I don't think it would break anything to restore it. I took it out mostly because as far as I could see it was only being used to transfer info about caching from `execute` to `executed`, and we don't do that anymore. And I think the test that examined it will still need to go away. So it really will be more or less unused. Fine with me either way though.

**Comment by bdbaddog** [comment]
> > One concern/question. Previously the node had `.cached` which you could use to see if the file was cached or not. Now there's only a check to see if it shouldn't be cached, but no way to tell if the node has actually been cached?
> > Would restoring .cached break anything in this change?
> 
> I don't think it would break anything to restore it. I took it out mostly because as far as I could see it was only being used to transfer info about caching from `execute` to `executed`, and we don't do that anymore. And I think the test that examined it will still need to go away. So it really will be more or less unused. Fine with me either way though.

I think it's worth adding back in. 
While not part of the published API, I can see someone useing it, and we may find it useful going forward with remote caching,etc..

**Comment by acmorrow** [comment]
> > > One concern/question. Previously the node had `.cached` which you could use to see if the file was cached or not. Now there's only a check to see if it shouldn't be cached, but no way to tell if the node has actually been cached?
> > > Would restoring .cached break anything in this change?
> > 
> > 
> > I don't think it would break anything to restore it. I took it out mostly because as far as I could see it was only being used to transfer info about caching from `execute` to `executed`, and we don't do that anymore. And I think the test that examined it will still need to go away. So it really will be more or less unused. Fine with me either way though.
> 
> I think it's worth adding back in. While not part of the published API, I can see someone useing it, and we may find it useful going forward with remote caching,etc..

@bdbaddog - done.

**Pull request merged**
