### PR TITLE
MINGW: Add missing directories to searched paths for mingw installs

### PR DESCRIPTION
**Pull request by maxbachmann**
This adds the `usr/bin` paths for `MINGW_DEFAULT_PATHS`. Without these paths `xgettext` is not found on my system.

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `CHANGES.txt` (and read the `README.rst`)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
Seems reasonable to me. Don't have an appropriate platform to check on. We have ongoing problems "guessing" paths of things on Windows, where they don't go into standard locations.

**Comment by mwichmann** [comment]
Hmmm, this has broken something in the Python 3.6 Windows build (which is provisioned with VS 2017 and Windows Server 2016).  Sometimes these are "not our fault", but should be investigated - the change in question shouldn't be able to have this effect.

https://ci.appveyor.com/project/SCons/scons/builds/47778467/job/yjs4sxhu9130rfex

**Comment by mwichmann** [comment]
Maybe this is the moment to reconcile the problem mentioned here:

https://github.com/SCons/scons/blob/e141cd3288ece58340a1a9e5d99a8c4f810366a9/SCons/Tool/mingw.py#L44

Namely that there's a list of search paths, used for slightly differing purposes, kept in two places, one in the platform code, one in the tool.

**Comment by maxbachmann** [comment]
`msys64\mingw64\bin` would work as well. The binary is both in `msys64\mingw64\bin` and `msys64\usr\bin`. So updating the list to the one in `Tool/mingw.py` would work.

**Comment by bdbaddog** [comment]
Merged! Thanks for the PR!!

**Pull request merged**
