### PR TITLE
Parse "-imacros" option in ParseFlags

### PR DESCRIPTION
**Pull request by ivankravets**
- https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html
- https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-imacros-file

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [x] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by mwichmann** [comment]
I don't see why `-imacros` shouldn't be supported here if `-include` is.  But this whole issue of adding partial support for gcc-specific features seems a little dodgy. scons still doesn't "know" about headers included this way (i.e. file scanner won't run on them). For `imacros` that sounds like it's probably okay, since the way I read the docs (never used this option), it only picks up the macros from the header thus included, and does not otherwise affect the dependency tree.

**Comment by ivankravets** [comment]
It's not only GCC related option. Clang supports it too https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-imacros-file

**Comment by mwichmann** [comment]
> It's not only GCC related option. Clang supports it too https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-imacros-file

So I was imprecise, probably should have said "compiler-specific", there wasn't any criticism in mentioning gcc.

By the way: scons has started failing `clang` tests on one Windows configuration, the one which uses the Visual Studio 2019 build image.  It didn't do that when we first turned on testing on that image, so presumably it has to do with changes in the image itself?  

https://www.appveyor.com/docs/windows-images-software/#llvm

suggests that the difference in the VS2019 image is it has none of the older LLVM/clang versions installed - but the problem actually seems not being pointed at appropriate headers.

This wasn't caused by your change, but is part of the reason the AppVeyor build is "failing". If you've got any ideas on that they'd be welcome!  (fine to move this off this issue and to mailing list or discord - only mentioned because (a) you brought up clang and (b) CI tests blip because of clang)

**Comment by bdbaddog** [comment]
Please add a test and update the docs.
There's a section in the manpage for ParseFlags which currently lists all the flags which get parsed.

**Comment by bdbaddog** [comment]
@ivankravets  - Ping. Can you add a test and update the docs. Then I'll be able to merge.

**Comment by ivankravets** [comment]
Sorry for the delay. Done! I also fixed the indention issue with 3 spaces for ParseFlags.

**Pull request merged**
