### PR TITLE
A feature request for nicer dep. tree printing

### PR DESCRIPTION
**Pull request by kurazsi**
Hello, 
Would it be possible to allow for a better rendering of the dependency tree ?
I implemented this change locally, and would really appreciate if i could generate this tree for documentation purposes.
Of course these have to be supported by the terminal that scons runs in. 
To combat this it would be possible to allow customization's from the project's via environmental variables.

## Remove this paragraph
Please have a look at our developer documentation before submitting your Pull Request.

https://scons.org/guidelines.html

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Definitely not opposition to improving the output.

Can you paste an example of the current and your new tree rendering?

Also you can removed the bit which says "REMOVE THIS PARAGRAPH"...

You'll need to add/update tests and update src/CHANGES.txt. It's possible there's some docs which need updating, but also possible not as most scons output in the docs is generated by running SCons and capturing the output.

(This the checklist in the default Pull Request template)

**Comment by kurazsi** [comment]
This is the original drawing:
```
+-validation/validationApps/testApp_1
  +-validation/validationApps/testApp_1
    +-validation/validationApps/testApp_1/app.elf
      +-validation/validationApps/testApp_1/auxiliaryFunctions.lib
      | +-validation/validationApps/testApp_1/common.lib
      |   +-validation/validationApps/system/libfile00.a
      |   | +-validation/validationApps/system/objectfile00.c.o
      |   | +-validation/validationApps/system/objectfile01.c.o
      |   | +-validation/validationApps/system/objectfile02.c.o
      |   | +-validation/validationApps/system/objectfile03.c.o
      |   | +-validation/validationApps/system/objectfile04.c.o
      |   | +-validation/validationApps/system/objectfile05.c.o
      |   | +-validation/validationApps/system/objectfile06.c.o
      |   | +-validation/validationApps/system/objectfile07.c.o
      |   | +-validation/validationApps/system/objectfile08.c.o
      |   | +-validation/validationApps/system/objectfile09.c.o
      |   | +-validation/validationApps/system/objectfile10.c.o
      |   | +-validation/validationApps/system/objectfile11.c.o
      |   +-validation/validationApps/system/libfile01.a
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      |     +-validation/validationApps/system/objectfile12.c.o
      +-validation/validationApps/testApp_1/main_app.lib
        +-validation/validationApps/testApp_1/main_op1.a
        | +-validation/validationApps/testApp_1/main_opAdd.a
        |   +-validation/validationApps/testApp_1/main_opAdd.c.o
        +-validation/validationApps/testApp_1/main_op2.a
        | +-validation/validationApps/testApp_1/main_opSub.a
        |   +-validation/validationApps/testApp_1/main_opSub.c.o
        +-[validation/validationApps/testApp_1/ext_op1.a]
        +-[validation/validationApps/testApp_1/ext_op2.a]
```

**Comment by kurazsi** [comment]
this is the new proposed one:
```
└─┬<itemObject>
  ├─┬<itemObject>
  │ ├─┬<itemObject>
  │ │ └─┬<itemObject>
  │ │   ├─┬<itemObject>
  │ │   │ └─┬<itemObject>
  │ │   │   ├─┬<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ └─<itemObject>
  │ │   │   └─┬<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     └─<itemObject>
  │ │   ├─┬<itemObject>
  │ │   │ └─┬<itemObject>
  │ │   │   ├─┬<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ ├─<itemObject>
  │ │   │   │ └─<itemObject>
  │ │   │   └─┬<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     ├─<itemObject>
  │ │   │     └─<itemObject>
  │ │   ├─┬<itemObject>
  │ │   │ ├─┬<itemObject>
  │ │   │ │ └─┬<itemObject>
  │ │   │ │   └─┬<itemObject>
  │ │   │ │     └─<itemObject>
  │ │   │ ├─┬<itemObject>
  │ │   │ │ └─┬<itemObject>
  │ │   │ │   └─<itemObject>
  │ │   │ ├──[<itemObject>]
  │ │   │ └──[<itemObject>]
  │ │   ├─┬<itemObject>
  │ │   │ ├─┬<itemObject>
  │ │   │ │ └─┬<itemObject>
  │ │   │ │   └─┬<itemObject>
  │ │   │ │     └─<itemObject>
  │ │   │ ├─┬<itemObject>
  │ │   │ │ └─┬<itemObject>
  │ │   │ │   └─<itemObject>
  │ │   │ ├──[<itemObject>]
  │ │   │ └──[<itemObject>]
  │ │   ├─┬<itemObject>
  │ │   │ └─<itemObject>
  │ │   ├──[<itemObject>]
  │ │   ├──[<itemObject>]
  │ │   ├──[<itemObject>]
  │ │   ├──[<itemObject>]
  │ │   └──[<itemObject>]
  │ └─┬<itemObject>
  │   ├─┬<itemObject>
  │   │ ├──[<itemObject>]
  │   │ └─<itemObject>
  │   └─┬<itemObject>
  │     ├─┬<itemObject>
  │     │ ├─┬<itemObject>
  │     │ │ ├──[<itemObject>]
  │     │ │ ├──[<itemObject>]
  │     │ │ ├──[<itemObject>]
  │     │ │ ├─<itemObject>
  │     │ │ ├─┬<itemObject>
  │     │ │ │ └──[<itemObject>]
  │     │ │ ├─┬<itemObject>
  │     │ │ │ ├─<itemObject>
  │     │ │ │ ├──[<itemObject>]
  │     │ │ │ └──[<itemObject>]
  │     │ │ └──[<itemObject>]
  │     │ └─┬<itemObject>
  │     │   ├──[<itemObject>]
  │     │   ├──[<itemObject>]
  │     │   ├──[<itemObject>]
  │     │   ├─<itemObject>
  │     │   ├─┬<itemObject>
  │     │   │ └──[<itemObject>]
  │     │   ├─┬<itemObject>
  │     │   │ ├─<itemObject>
  │     │   │ ├──[<itemObject>]
  │     │   │ └──[<itemObject>]
  │     │   └──[<itemObject>]
  │     └─┬<itemObject>
  │       ├─┬<itemObject>
  │       │ ├──[<itemObject>]
  │       │ ├──[<itemObject>]
  │       │ ├─┬<itemObject>
  │       │ │ └──[<itemObject>]
  │       │ ├─┬<itemObject>
  │       │ │ ├─<itemObject>
  │       │ │ ├─<itemObject>
  │       │ │ ├─<itemObject>
  │       │ │ ├─<itemObject>
  │       │ │ ├─<itemObject>
  │       │ │ └──[<itemObject>]
  │       │ └─┬<itemObject>
  │       │   ├─<itemObject>
  │       │   ├─<itemObject>
  │       │   ├─<itemObject>
  │       │   ├─<itemObject>
  │       │   └──[<itemObject>]
  │       └─┬<itemObject>
  │         ├──[<itemObject>
  │         ├──[<itemObject>
  │         ├─┬<itemObject>
  │         │ └──[<itemObject>]
  │         ├─┬<itemObject>
  │         │ ├─<itemObject>
  │         │ ├─<itemObject>
  │         │ ├─<itemObject>
  │         │ ├─<itemObject>
  │         │ ├─<itemObject>
  │         │ └──[<itemObject>]
  │         └─┬<itemObject>
  │           ├─<itemObject>
  │           └──[<itemObject>]
  └─┬<itemObject>
    ├─<itemObject>
    └─<itemObject>

```

**Comment by bdbaddog** [comment]
Nice.
If you add a blurb to src/CHANGES.txt and fix any tests which break due to this change we should be able to merge this.

**Comment by kurazsi** [comment]
This PR has been recreated here:
https://github.com/SCons/scons/pull/3560 
moved to a proper branch where i can create a full implementation of this feature, as requested...

**Comment by kurazsi** [comment]
> Nice.
> If you add a blurb to src/CHANGES.txt and fix any tests which break due to this change we should be able to merge this.

Yes, it's a small group of ppl together we are going to add all requested changes, in a new PR i opened.

**Pull request closed without merging**
