### PR TITLE
Fix nasm test

### PR DESCRIPTION
**Pull request by mwichmann**
Fix reported problem of missing header (no declaration for exit()). Clean up to current styles.

Test-only change.

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [X] I have updated `CHANGES.txt` and `RELEASE.txt` (and read the `README.rst`).
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
Can you add a release.txt blurb and callout that it was fixed for issue found by debian packager?

**Comment by mwichmann** [comment]
didn't seem useful for release, no user will ever see that

**Comment by bdbaddog** [comment]
> didn't seem useful for release, no user will ever see that

This is a fix for the debian packager, so he'll see it..

**Comment by mwichmann** [comment]
> > didn't seem useful for release, no user will ever see that
> 
> This is a fix for the debian packager, so he'll see it..

Pushed

**Pull request merged**
