### PR TITLE
Let test runner use new Dev. Mode

### PR DESCRIPTION
**Pull request by mwichmann**
Python Development Mode imposes more checks (since Python 3.7). Allow it to optionally be enabled while doing a test run.

Adding ```-D --devmode```
Enables Python's new (3.7 an above)

**From Python's Docs**
-X dev: enable CPython’s “development mode”, introducing additional runtime checks which are too expensive to be enabled by default. It should not be more verbose than the default if the code is correct: new warnings are only emitted when an issue is detected. Effect of the developer mode: 

  -  Add default warning filter, as -W default.
  -  Install debug hooks on memory allocators: see the PyMem_SetupDebugHooks() C function.
  -  Enable the faulthandler module to dump the Python traceback on a crash.
  -  Enable asyncio debug mode.
  -  Set the dev_mode attribute of sys.flags to True.
  -  io.IOBase destructor logs close() exceptions.

This is a test (runner) only change.

Signed-off-by: Mats Wichmann <mats@linux.com>

## Contributor Checklist:

* [X] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by bdbaddog** [comment]
What extra checking does it turn on?

**Comment by mwichmann** [comment]
https://docs.python.org/3.9/library/devmode.html#devmode

**Comment by bdbaddog** [comment]
Would it make sense to set [PYTHONDEVMODE](https://docs.python.org/dev/using/cmdline.html#envvar-PYTHONDEVMODE) in addition or instead so sub processes also would run in dev mode?

**Comment by mwichmann** [comment]
I suppose... I thought we hated env vars for things, though?  FIXTURE_DIRS set by runtest works because the framework fishes it out and saves the data in an instance variable... would that need to be recognized and propagated by the harness too?

**Comment by bdbaddog** [comment]
> I suppose... I thought we hated env vars for things, though? FIXTURE_DIRS set by runtest works because the framework fishes it out and saves the data in an instance variable... would that need to be recognized and propagated by the harness too?

SCons prefers that builds aren't influenced by user's shell environment variables by default (if at all possible). 
In this case it's the testing framework (not the users builds), so when useful it's o.k.
That said. I'm not sure about having SCons by default propagate PYTHONDEVMODE to it's sub processes..
Which might be necessary to get the testing to propagate.

**Pull request merged**
