### PR TITLE
[WIP] Prototype of a more aggressive parallel scanner

### PR DESCRIPTION
**Pull request by grossag**
This is a work-in-progress changeset for a more aggressive parallel scanner.
The current parallel scanner wastes time waiting for thread pool results when
it could have been more aggressively continuing to gather more tasks to
dispatch. The idea here is that if we have dispatched the maximum number of
jobs and none are done yet, we should gather more tasks instead of doing a
blocking wait on the thread pool. In my testing, I have seen a 4-5% improvement
in some VMware builds.

One upside of this change is that it paves the way for us to be able to
implement remote caching because we now ask the cache for groups of tasks
instead of one-at-a-time.

At VMware we don't have a good mechanism for testing upstream SCons changes so
this is a blind application of a patch I wrote. It passes some tests but
may have some bugs compared to the version I applied internally. More work
needed here; for now I just want to get people's thoughts on whether this is heading in the right direction.

## Contributor Checklist:

* [ ] I have created a new test or updated the unit tests to cover the new/changed functionality.
* [ ] I have updated `master/src/CHANGES.txt` directory (and read the `README.txt` in that directory)
* [ ] I have updated the appropriate documentation

### CODE REVIEW

**Comment by acmorrow** [comment]
@grossag - Improvements here seem to be of interest recently. Have you had a look at my proposed #3386?

**Comment by bdbaddog** [comment]
@grossag  - What version of SCons are you running internally?

**Comment by bdbaddog** [comment]
Looks like you have some code errors?
```
NameError: global name 'ParallelV2' is not defined:
  File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1374:
    _exec_main(parser, values)
  File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1337:
    _main(parser)
  File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1112:
    nodes = _build_targets(fs, options, targets, target_top)
  File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1273:
    jobs = SCons.Job.Jobs(num_jobs, taskmaster, options.parallel_v2)
  File "/home/travis/build/SCons/scons/src/engine/SCons/Job.py", line 113:
    taskmaster.set_tm_owns_caching(not isinstance(self.job, ParallelV2))
```

**Comment by grossag** [comment]
> Looks like you have some code errors?
> 
> ```
> NameError: global name 'ParallelV2' is not defined:
>   File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1374:
>     _exec_main(parser, values)
>   File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1337:
>     _main(parser)
>   File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1112:
>     nodes = _build_targets(fs, options, targets, target_top)
>   File "/home/travis/build/SCons/scons/src/engine/SCons/Script/Main.py", line 1273:
>     jobs = SCons.Job.Jobs(num_jobs, taskmaster, options.parallel_v2)
>   File "/home/travis/build/SCons/scons/src/engine/SCons/Job.py", line 113:
>     taskmaster.set_tm_owns_caching(not isinstance(self.job, ParallelV2))
> ```

Good catch. I haven't tested it a lot yet; mostly just wanted to get a conversation started. That said, I did attempt to resolve the issue with another commit just now.

**Comment by grossag** [comment]
> @grossag - What version of SCons are you running internally?

We are running SCons 2.0.1 with a few custom patches on top and a lot of VMware-specific overrides. We are working internally on updating to 2.5 and then to 3.0 and hope to have that done in the next few months.

**Comment by grossag** [comment]
> @grossag - Improvements here seem to be of interest recently. Have you had a look at my proposed #3386?

Thanks for linking to this @acmorrow. I looked just now but I think that your change does not attempt to address the main issue I'm concerned about. Specifically, your change still waits on a job to be ready if jobs==self.maxjobs, while I think the big performance improvements will come if we only wait if task==None.

**Comment by bdbaddog** [comment]
> > @grossag - What version of SCons are you running internally?
> 
> We are running SCons 2.0.1 with a few custom patches on top and a lot of VMware-specific overrides. We are working internally on updating to 2.5 and then to 3.0 and hope to have that done in the next few months.

Skip 3.0.0 and go to either 3.0.5, or 3.1 (to be released soon) Some performance improvements in 3.1. 3.0.0 had minor issues with print() and py2/py3. so definitely skip that.

**Comment by bdbaddog** [comment]
> > > @grossag - What version of SCons are you running internally?
> > 
> > 
> > We are running SCons 2.0.1 with a few custom patches on top and a lot of VMware-specific overrides. We are working internally on updating to 2.5 and then to 3.0 and hope to have that done in the next few months.
> 
> Skip 3.0.0 and go to either 3.0.5, or 3.1 (to be released soon) Some performance improvements in 3.1. 3.0.0 had minor issues with print() and py2/py3. so definitely skip that.

Can you push your current scons code to github repo somewhere?
Be interested to see what changes you've made and if any would be useful to the rest of the scons community

**Comment by acmorrow** [comment]
> > @grossag - Improvements here seem to be of interest recently. Have you had a look at my proposed #3386?
> 
> Thanks for linking to this @acmorrow. I looked just now but I think that your change does not attempt to address the main issue I'm concerned about. Specifically, your change still waits on a job to be ready if jobs==self.maxjobs, while I think the big performance improvements will come if we only wait if task==None.

That is true, but I would think of that as basically equivalent to just running with -j 1000000 or some huge number under my model. My model came into being when I was looking at how SCons behaved with a large -j number in an icecream cluster. It would spend basically all of its time trying to achieve the target concurrency, building up a huge backlog of uncollected tasks until it literally couldn't find another, and only then collect more. Essentially, SCons just couldn't find enough parallel work in our tree to come close to saturating the clusters compute capacity.

The idea in my change is to try to find a balance, where you consume jobs when they are ready such that you are more likely to make it easy to find new jobs. So the target concurrency becomes aspirational, not required.

If you don't mind giving it a try, I'd be interested to know how much (if any) of your observed 4-5% you see trying my approach with a large -j value.

> One upside of this change is that it paves the way for us to be able to
implement remote caching because we now ask the cache for groups of tasks
instead of one-at-a-time.

I'd like to understand a little better what you have changed and what motivated it. We are currently using remote shared caching on both Linux and Windows with some success, simply via a shared network file-system. But we are certainly interested in improvements!

**Comment by grossag** [comment]
Going to work on another version that will integrate with Bazel remote cache server. Will post another pull request in a few weeks to solicit feedback.

**Pull request closed without merging**
